CREATE TABLE register (
  id INT(6)(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(30) NOT NULL,
  lastname VARCHAR(30) NOT NULL,
  username VARCHAR(30) NOT NULL,
  city VARCHAR(50) NOT NULL,
  state VARCHAR(50) NOT NULL,
  zip VARCHAR(20) NOT NULL
)
<<<<<<< HEAD

CREATE TABLE transaction (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  a INT(6) NOT NULL,
  b INT(6) NOT NULL,
  c INT(6) NOT NULL,
  d INT(6) NOT NULL,
  e INT(6) NOT NULL,
  f INT(6) NOT NULL,
  g INT(6) NOT NULL,
  h INT(6) NOT NULL,
  i INT(6) NOT NULL,
  j INT(6) NOT NULL,
  total INT(6) NOT NULL
) 



  username VARCHAR(30) NOT NULL,
  city VARCHAR(50) NOT NULL,
  state VARCHAR(50) NOT NULL,
  zip VARCHAR(20) NOT NULL
)


11 11 11 11 111
=======
>>>>>>> 3e1100741c4dafe1a7ee0c31be94d3151edcc1d8
